timestamp,category,user_id,function,line_number,flag,message,exception
2024-06-14 15:44:49,ERROR,rahul17,create_or_pass_folder,202,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\app.py"", line 195, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:38c15e5f-501e-0003-2f43-be7601000000
Time:2024-06-14T10:14:49.4993449Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:rahul17
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:38c15e5f-501e-0003-2f43-be7601000000
Time:2024-06-14T10:14:49.4993449Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>rahul17</QueryParameterValue></Error>"
2024-06-14 15:44:49,ERROR,rahul17,create_or_pass_folder,211,0,"Function create_or_pass_folder Error creating folder'rahul17': Value for one of the query parameters specified in the request URI is invalid.
RequestId:38c15e5f-501e-0003-2f43-be7601000000
Time:2024-06-14T10:14:49.4993449Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:rahul17
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:38c15e5f-501e-0003-2f43-be7601000000
Time:2024-06-14T10:14:49.4993449Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>rahul17</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'rahul17': Value for one of the query parameters specified in the request URI is invalid.
RequestId:38c15e5f-501e-0003-2f43-be7601000000
Time:2024-06-14T10:14:49.4993449Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:rahul17
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:38c15e5f-501e-0003-2f43-be7601000000
Time:2024-06-14T10:14:49.4993449Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>rahul17</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\app.py"", line 195, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:38c15e5f-501e-0003-2f43-be7601000000
Time:2024-06-14T10:14:49.4993449Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:rahul17
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:38c15e5f-501e-0003-2f43-be7601000000
Time:2024-06-14T10:14:49.4993449Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>rahul17</QueryParameterValue></Error>"
2024-06-14 15:44:49,INFO,rahul17,home,1411,1,User rahul17 logged in successfully,
2024-06-14 15:44:49,INFO,rahul17,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-14 15:44:53,INFO,rahul17,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-14 15:44:55,INFO,rahul17,get_data_source,2284,1,table_update route successfully send data,
2024-06-14 15:44:57,INFO,rahul17,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-14 15:44:59,INFO,rahul17,get_data_source,2284,1,table_update route successfully send data,
2024-06-14 15:45:01,INFO,rahul17,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-14 15:45:03,INFO,rahul17,get_data_source,2284,1,table_update route successfully send data,
2024-06-14 15:45:13,INFO,rahul17,upload_to_blob,260,1,Function upload_to_blob successfully created blob_client.url,
2024-06-14 15:45:13,INFO,rahul17,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-14 15:45:13,INFO,rahul17,popup_form,1543,1,Data Uploaded Successfully,
2024-06-14 15:45:14,INFO,rahul17,Cogni_button,1726,1,CogniLink load button pressed,
2024-06-14 15:45:15,INFO,rahul17,get_data_source,2284,1,table_update route successfully send data,
2024-06-14 15:45:29,ERROR,rahul17,handle_summary_input,1989,0,Summary generation error,"Summary generation error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\app.py"", line 1976, in handle_summary_input
    analyze_sentiment_summ(senti_text_summ)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\app.py"", line 921, in analyze_sentiment_summ
    senti_Positive_summ = sentiment_scores['pos'] / total * 100
ZeroDivisionError: float division by zero"
2024-06-14 15:45:32,INFO,rahul17,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-14 15:45:34,INFO,rahul17,update_when_file_delete,602,1,Function update_when_file_delete Data Loaded Successfully,
2024-06-14 15:45:34,INFO,rahul17,Cogni_button,1738,1,Load Data Function executed in 20.134753704071045 seconds,
2024-06-14 15:46:09,INFO,rahul17,perform_lda____summ,1133,1,Summary topics generated.,
2024-06-14 15:46:09,INFO,rahul17,handle_summary_input,1983,1,Summary Generated in 22.052405834197998 seconds,
2024-06-14 15:46:53,INFO,rahul17,handle_clear_chat_summ,2017,1,Summary chat cleared,
2024-06-14 15:46:55,INFO,rahul17,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-14 15:46:58,INFO,rahul17,get_data_source,2284,1,table_update route successfully send data,
