timestamp,category,user_id,function,line_number,flag,message,exception
2024-06-10 12:00:40,ERROR,asif24,create_or_pass_folder,199,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 192, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:ba76c164-601e-004f-4fff-bab11e000000
Time:2024-06-10T06:30:39.5419321Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:ba76c164-601e-004f-4fff-bab11e000000
Time:2024-06-10T06:30:39.5419321Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-06-10 12:00:40,ERROR,asif24,create_or_pass_folder,208,0,"Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:ba76c164-601e-004f-4fff-bab11e000000
Time:2024-06-10T06:30:39.5419321Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:ba76c164-601e-004f-4fff-bab11e000000
Time:2024-06-10T06:30:39.5419321Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:ba76c164-601e-004f-4fff-bab11e000000
Time:2024-06-10T06:30:39.5419321Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:ba76c164-601e-004f-4fff-bab11e000000
Time:2024-06-10T06:30:39.5419321Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 192, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:ba76c164-601e-004f-4fff-bab11e000000
Time:2024-06-10T06:30:39.5419321Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:ba76c164-601e-004f-4fff-bab11e000000
Time:2024-06-10T06:30:39.5419321Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-06-10 12:00:40,INFO,asif24,home,1408,1,User asif24 logged in successfully,
2024-06-10 12:00:40,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 12:00:43,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 12:00:48,INFO,asif24,get_data_source,2079,1,table_update route successfully send data,
2024-06-10 12:00:51,ERROR,asif24,handle_summary_input,1881,0,Summary generation error,"Summary generation error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 1837, in handle_summary_input
    summary = custom_summary(document, custom_p, chain_type)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 835, in custom_summary
    summaries = chain({""input_documents"": docs}, return_only_outputs=True)[""output_text""]
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\langchain_core\_api\deprecation.py"", line 148, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\langchain\chains\base.py"", line 378, in __call__
    return self.invoke(
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\langchain\chains\base.py"", line 163, in invoke
    raise e
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\langchain\chains\base.py"", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\langchain\chains\combine_documents\base.py"", line 137, in _call
    output, extra_return_dict = self.combine_docs(
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\langchain\chains\combine_documents\map_reduce.py"", line 228, in combine_docs
    [{self.document_variable_name: d.page_content, **kwargs} for d in docs],
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\langchain\chains\combine_documents\map_reduce.py"", line 228, in <listcomp>
    [{self.document_variable_name: d.page_content, **kwargs} for d in docs],
AttributeError: 'str' object has no attribute 'page_content'"
