timestamp,category,user_id,function,line_number,flag,message,exception
2024-07-09 17:01:48,ERROR,asif24,create_or_pass_folder,232,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\app.py"", line 225, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:f97f5f2b-b01e-0064-34f3-d1c5a6000000
Time:2024-07-09T11:31:48.7506802Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:f97f5f2b-b01e-0064-34f3-d1c5a6000000
Time:2024-07-09T11:31:48.7506802Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-07-09 17:01:48,ERROR,asif24,create_or_pass_folder,241,0,"Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:f97f5f2b-b01e-0064-34f3-d1c5a6000000
Time:2024-07-09T11:31:48.7506802Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:f97f5f2b-b01e-0064-34f3-d1c5a6000000
Time:2024-07-09T11:31:48.7506802Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:f97f5f2b-b01e-0064-34f3-d1c5a6000000
Time:2024-07-09T11:31:48.7506802Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:f97f5f2b-b01e-0064-34f3-d1c5a6000000
Time:2024-07-09T11:31:48.7506802Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\app.py"", line 225, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:f97f5f2b-b01e-0064-34f3-d1c5a6000000
Time:2024-07-09T11:31:48.7506802Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:f97f5f2b-b01e-0064-34f3-d1c5a6000000
Time:2024-07-09T11:31:48.7506802Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-07-09 17:01:48,INFO,asif24,home,1789,1,User asif24 logged in successfully,
2024-07-09 17:01:48,INFO,asif24,update_bar_chart_from_blob,419,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-09 17:01:54,INFO,asif24,update_bar_chart_from_blob,419,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-09 17:01:59,INFO,asif24,update_bar_chart_from_blob,419,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-09 17:01:59,INFO,asif24,table_update,3241,1,table_update route successfully sent data in 2.7501134872436523 seconds,
2024-07-09 17:02:03,INFO,asif24,analyze_sentiment_summ,1271,1,Summary sentiments analyzed,
2024-07-09 17:02:03,ERROR,asif24,handle_summary_input,2777,0,Summary generation error,"Summary generation error
Traceback (most recent call last):
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\app.py"", line 2766, in handle_summary_input
    generate_word_cloud(senti_text_summ)
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\app.py"", line 898, in generate_word_cloud
    min_font_size=10).generate(' '.join(tokens))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\wordcloud\wordcloud.py"", line 642, in generate
    return self.generate_from_text(text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\wordcloud\wordcloud.py"", line 624, in generate_from_text
    self.generate_from_frequencies(words)
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\wordcloud\wordcloud.py"", line 453, in generate_from_frequencies
    self.generate_from_frequencies(dict(frequencies[:2]),
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\wordcloud\wordcloud.py"", line 506, in generate_from_frequencies
    font = ImageFont.truetype(self.font_path, font_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\PIL\ImageFont.py"", line 834, in truetype
    return freetype(font)
           ^^^^^^^^^^^^^^
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\PIL\ImageFont.py"", line 831, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\PIL\ImageFont.py"", line 257, in __init__
    self.font = core.getfont(
                ^^^^^^^^^^^^^
OSError: cannot open resource"
2024-07-09 17:02:15,INFO,asif24,handle_clear_chat_summ,2805,1,Summary chat cleared,
