timestamp,category,user_id,function,line_number,flag,message,exception
2024-07-08 18:12:27,ERROR,asif24,create_or_pass_folder,233,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\app.py"", line 226, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:f310b5d9-301e-0018-1334-d15893000000
Time:2024-07-08T12:42:25.9661416Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:f310b5d9-301e-0018-1334-d15893000000
Time:2024-07-08T12:42:25.9661416Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-07-08 18:12:27,ERROR,asif24,create_or_pass_folder,242,0,"Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:f310b5d9-301e-0018-1334-d15893000000
Time:2024-07-08T12:42:25.9661416Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:f310b5d9-301e-0018-1334-d15893000000
Time:2024-07-08T12:42:25.9661416Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:f310b5d9-301e-0018-1334-d15893000000
Time:2024-07-08T12:42:25.9661416Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:f310b5d9-301e-0018-1334-d15893000000
Time:2024-07-08T12:42:25.9661416Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\app.py"", line 226, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:f310b5d9-301e-0018-1334-d15893000000
Time:2024-07-08T12:42:25.9661416Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:f310b5d9-301e-0018-1334-d15893000000
Time:2024-07-08T12:42:25.9661416Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-07-08 18:12:27,INFO,asif24,home,1752,1,User asif24 logged in successfully,
2024-07-08 18:12:27,INFO,asif24,update_bar_chart_from_blob,420,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-08 18:12:30,INFO,asif24,update_bar_chart_from_blob,420,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-08 18:12:34,INFO,asif24,update_bar_chart_from_blob,420,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-08 18:12:34,INFO,asif24,table_update,3081,1,table_update route successfully sent data,
2024-07-08 18:12:42,INFO,asif24,upload_to_blob,302,1,Function upload_to_blob successfully uploaded the blob,
2024-07-08 18:12:42,INFO,asif24,upload_to_blob,305,1,Function upload_to_blob successfully uploaded the blob,
2024-07-08 18:12:43,INFO,asif24,update_bar_chart_from_blob,420,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-08 18:12:43,INFO,asif24,popup_form,2203,1,Data Uploaded Successfully,
2024-07-08 18:12:46,INFO,asif24,update_bar_chart_from_blob,420,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-08 18:12:46,ERROR,asif24,table_update,3087,0,table_update route error,"table_update route error
Traceback (most recent call last):
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\app.py"", line 3078, in table_update
    socketio.emit('updateTable', data)
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\flask_socketio\__init__.py"", line 462, in emit
    self.server.emit(event, *args, namespace=namespace, to=to,
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\socketio\server.py"", line 166, in emit
    self.manager.emit(event, data, namespace, room=room,
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\socketio\manager.py"", line 43, in emit
    encoded_packet = pkt.encode()
                     ^^^^^^^^^^^^
  File ""C:\Users\Asif Ansari.DESKTOP-TFHGSOM\Desktop\dev-letest-code\Test_Load\.venv\Lib\site-packages\socketio\packet.py"", line 64, in encode
    encoded_packet += self.json.dumps(data, separators=(',', ':'))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""C:\Program Files\Python311\Lib\json\__init__.py"", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File ""C:\Program Files\Python311\Lib\json\encoder.py"", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""C:\Program Files\Python311\Lib\json\encoder.py"", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File ""C:\Program Files\Python311\Lib\json\encoder.py"", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable"
