timestamp,category,user_id,function,line_number,flag,message,exception
2024-07-03 13:24:02,ERROR,asif24,create_or_pass_folder,226,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 219, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:77314bb6-b01e-0002-5d1e-cd77fc000000
Time:2024-07-03T07:54:01.7322143Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:77314bb6-b01e-0002-5d1e-cd77fc000000
Time:2024-07-03T07:54:01.7322143Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-07-03 13:24:02,ERROR,asif24,create_or_pass_folder,235,0,"Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:77314bb6-b01e-0002-5d1e-cd77fc000000
Time:2024-07-03T07:54:01.7322143Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:77314bb6-b01e-0002-5d1e-cd77fc000000
Time:2024-07-03T07:54:01.7322143Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:77314bb6-b01e-0002-5d1e-cd77fc000000
Time:2024-07-03T07:54:01.7322143Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:77314bb6-b01e-0002-5d1e-cd77fc000000
Time:2024-07-03T07:54:01.7322143Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 219, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:77314bb6-b01e-0002-5d1e-cd77fc000000
Time:2024-07-03T07:54:01.7322143Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:77314bb6-b01e-0002-5d1e-cd77fc000000
Time:2024-07-03T07:54:01.7322143Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-07-03 13:24:02,INFO,asif24,home,1704,1,User asif24 logged in successfully,
2024-07-03 13:24:02,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:24:05,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:24:08,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:24:08,INFO,asif24,get_data_source,3131,1,table_update route successfully sent data,
2024-07-03 13:24:11,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:24:11,INFO,asif24,popup_form,2155,1,Data Uploaded Successfully,
2024-07-03 13:24:13,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:24:13,INFO,asif24,get_data_source,3131,1,table_update route successfully sent data,
2024-07-03 13:24:24,INFO,asif24,Cogni_button,2338,1,CogniLink load button pressed,
2024-07-03 13:24:35,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:24:51,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:24:51,INFO,asif24,update_when_file_delete,778,1,Function update_when_file_delete Data Loaded Successfully,
2024-07-03 13:24:51,INFO,asif24,Cogni_button,2350,1,Load Data Function executed in 27.108980417251587 seconds,
2024-07-03 13:24:55,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:24:55,INFO,asif24,get_data_source,3131,1,table_update route successfully sent data,
2024-07-03 13:25:18,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:25:18,INFO,asif24,get_data_source,3131,1,table_update route successfully sent data,
2024-07-03 13:25:19,ERROR,asif24,delete_files,2812,0,delete for delete route error,"delete for delete route error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 2798, in delete_files
    blob_client.delete_blob()
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 1211, in delete_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 1209, in delete_blob
    self._client.blob.delete(**options)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_generated\operations\_blob_operations.py"", line 2116, in delete
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\core\exceptions.py"", line 165, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: The specified blob does not exist.
RequestId:eb5e2209-501e-004c-6e1e-cdb219000000
Time:2024-07-03T07:55:18.2313354Z
ErrorCode:BlobNotFound
Content: <?xml version=""1.0"" encoding=""utf-8""?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:eb5e2209-501e-004c-6e1e-cdb219000000
Time:2024-07-03T07:55:18.2313354Z</Message></Error>"
2024-07-03 13:25:19,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:25:19,INFO,asif24,delete_files,2808,1,Selected vault files deleted successfully,
2024-07-03 13:25:20,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:25:20,INFO,asif24,get_data_source,3131,1,table_update route successfully sent data,
2024-07-03 13:25:22,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:25:22,INFO,asif24,get_data_source,3131,1,table_update route successfully sent data,
2024-07-03 13:25:24,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:25:24,INFO,asif24,get_data_source,3131,1,table_update route successfully sent data,
2024-07-03 13:26:47,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:26:47,INFO,asif24,popup_form,2155,1,Data Uploaded Successfully,
2024-07-03 13:26:49,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:26:49,INFO,asif24,get_data_source,3131,1,table_update route successfully sent data,
