timestamp,category,user_id,function,line_number,flag,message,exception
2024-06-08 11:58:58,ERROR,asif24,create_or_pass_folder,197,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 190, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:b21d8259-701e-0014-6f6d-b9b662000000
Time:2024-06-08T06:28:57.0041716Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b21d8259-701e-0014-6f6d-b9b662000000
Time:2024-06-08T06:28:57.0041716Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-06-08 11:58:58,ERROR,asif24,create_or_pass_folder,206,0,"Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:b21d8259-701e-0014-6f6d-b9b662000000
Time:2024-06-08T06:28:57.0041716Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b21d8259-701e-0014-6f6d-b9b662000000
Time:2024-06-08T06:28:57.0041716Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:b21d8259-701e-0014-6f6d-b9b662000000
Time:2024-06-08T06:28:57.0041716Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b21d8259-701e-0014-6f6d-b9b662000000
Time:2024-06-08T06:28:57.0041716Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 190, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:b21d8259-701e-0014-6f6d-b9b662000000
Time:2024-06-08T06:28:57.0041716Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b21d8259-701e-0014-6f6d-b9b662000000
Time:2024-06-08T06:28:57.0041716Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-06-08 11:58:58,INFO,asif24,home,1393,1,User asif24 logged in successfully,
2024-06-08 11:58:58,INFO,asif24,update_bar_chart_from_blob,317,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-08 11:58:58,INFO,asif24,update_bar_chart_from_blob,317,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-08 11:59:00,INFO,asif24,get_data_source,1983,1,table_update route successfully send data,
2024-06-08 11:59:10,INFO,asif24,Cogni_button,1700,1,CogniLink load button pressed,
2024-06-08 12:00:17,INFO,asif24,update_bar_chart_from_blob,317,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-08 12:00:53,INFO,asif24,get_data_source,1983,1,table_update route successfully send data,
2024-06-08 12:00:54,INFO,asif24,get_data_source,1983,1,table_update route successfully send data,
2024-06-08 12:00:57,INFO,asif24,update_bar_chart_from_blob,317,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-08 12:00:57,INFO,asif24,delete_files,1945,1,Selected vault files deleted successfully,
2024-06-08 12:00:58,INFO,asif24,get_data_source,1983,1,table_update route successfully send data,
2024-06-08 12:01:53,INFO,asif24,update_bar_chart_from_blob,317,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-08 12:01:56,INFO,asif24,update_when_file_delete,592,1,Function update_when_file_delete Data Loaded Successfully,
2024-06-08 12:01:56,INFO,asif24,Cogni_button,1712,1,Load Data Function executed in 165.60486102104187 seconds,
2024-06-08 12:01:57,INFO,asif24,get_data_source,1983,1,table_update route successfully send data,
2024-06-08 12:02:19,INFO,asif24,Cogni_button,1700,1,CogniLink load button pressed,
2024-06-08 12:02:22,ERROR,asif24,Cogni_button,1720,0,Unhandled exception occurred,"Unhandled exception occurred
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 1704, in Cogni_button
    response = update_when_file_delete()
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 396, in update_when_file_delete
    embeddings_list = result['documents']
KeyError: 'documents'"
2024-06-08 12:04:08,INFO,asif24,get_data_source,1983,1,table_update route successfully send data,
2024-06-08 12:04:09,INFO,asif24,get_data_source,1983,1,table_update route successfully send data,
2024-06-08 12:04:32,INFO,asif24,update_bar_chart_from_blob,317,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-08 12:04:32,INFO,asif24,delete_files,1945,1,Selected vault files deleted successfully,
2024-06-08 12:04:33,INFO,asif24,get_data_source,1983,1,table_update route successfully send data,
2024-06-08 12:05:55,INFO,asif24,upload_to_blob,255,1,Function upload_to_blob successfully created blob_client.url,
2024-06-08 12:05:56,INFO,asif24,update_bar_chart_from_blob,317,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-08 12:05:56,INFO,asif24,popup_form,1517,1,Data Uploaded Successfully,
2024-06-08 12:05:56,INFO,asif24,get_data_source,1983,1,table_update route successfully send data,
